### PR TITLE
Update styles.css

### PR DESCRIPTION
**Pull request by joshwong21**

### CODE REVIEW

**Comment by joshwong21** [comment]
Please Kai

**Comment by joshwong21** [comment]
Im on my knees

**Comment by joshwong21** [comment]
https://juliakovach.files.wordpress.com/2012/06/man-on-his-knees1.jpg

**Comment by joshwong21** [comment]
Please

**Comment by joshwong21** [comment]
Be Reasonable

**Comment by joshwong21** [comment]
Dont be a bad person

**Comment by joshwong21** [comment]
Orsons Farm

**Comment by KBKracker** [comment]
NO

**Comment by joshwong21** [comment]
NOOOOOO

**Comment by joshwong21** [comment]
Just do it

**Comment by joshwong21** [comment]
NIke

**Comment by joshwong21** [comment]
Nike wants you to do it

**Comment by joshwong21** [comment]
What would your mom want you to do

**Comment by joshwong21** [comment]
Eat it

**Comment by MackY21** [comment]
Shia Le Buf will be proud if you do it...

**Comment by MackY21** [comment]
Il give you a cookie

**Comment by joshwong21** [comment]
Your mom wants you to

**Comment by joshwong21** [comment]
Morgan ate his sandwich on his cheeeseseseseseses and spiiiiiiiiiiiiiiiices
then he died in a fire and was reborn as chowder

On Tue, Jun 30, 2015 at 11:12 AM, KBKracker notifications@github.com
wrote:

> Merged #2 https://github.com/KBKracker/newProject/pull/2.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/KBKracker/newProject/pull/2#event-344703757.

## 

Squiggly-wiggly slippery fishy fish

**Pull request merged**
